// const - this is module for common constants

const RETAILER_ALPHANUMERIC = 'Target';
const RETAILER_NON_ALPHANUMERIC = '   ';

const BONUS_PURCHASE_DATE = "2022-01-01";
const NON_BONUS_PURCHASE_DATE = "2022-01-02";

const BONUS_PURCHASE_TIME = "14:13";
const NON_BONUS_PURCHASE_TIME = "08:13";

const BONUS_TOTAL = "1.00";
const NON_BONUS_TOTAL = "1.23";

const BONUS_ITEM_DESC_LENGTH_MULTIPLE = 3;
const BONUS_ITEM_DESC = "AbcDef";
const NON_BONUS_ITEM_DESC = "GE";

const AWARD_POINTS_ITEM_DESC_MULTIPLE = 0.2;


const AWARD_POINTS_ALPHANUMERIC = 1;
const AWARD_POINTS_TOTAL_ROUND = 50;

const AWARD_POINTS_TOTAL_MULTIPLE = 25;
const AWARD_POINTS_FOR_ITEMS_COUNT = 5;

const AWARD_POINTS_FOR_ITEMS_LEN = 3;
const AWARD_POINTS_FOR_ITEMS_LEN_PRICE = 0.2;

const AWARD_POINTS_FOR_TIME_RANGE = 10;

const AWARD_POINTS_FOR_PURCHASE_DATE = 6;
const AWARD_POINTS_FOR_EVERY_TWO_ITEMS = 5;

module.exports = {
    RETAILER_ALPHANUMERIC,
    RETAILER_NON_ALPHANUMERIC,
    BONUS_PURCHASE_TIME,
    NON_BONUS_PURCHASE_TIME,
    BONUS_PURCHASE_DATE,
    NON_BONUS_PURCHASE_DATE,
    BONUS_TOTAL,
    NON_BONUS_TOTAL,
    BONUS_ITEM_DESC,
    NON_BONUS_ITEM_DESC,
    BONUS_ITEM_DESC_LENGTH_MULTIPLE,
    //
    AWARD_POINTS_TOTAL_ROUND,
    AWARD_POINTS_TOTAL_MULTIPLE,
    AWARD_POINTS_ALPHANUMERIC,
    AWARD_POINTS_ITEM_DESC_MULTIPLE,
    AWARD_POINTS_FOR_ITEMS_COUNT,
    AWARD_POINTS_FOR_ITEMS_LEN,
    AWARD_POINTS_FOR_ITEMS_LEN_PRICE,
    AWARD_POINTS_FOR_TIME_RANGE,
    AWARD_POINTS_FOR_PURCHASE_DATE,
    AWARD_POINTS_FOR_EVERY_TWO_ITEMS,
};
